#apiVersion: v1
#kind: Secret
#metadata:
#  name: kruise-admin-token
#  namespace: kruise
#  annotations:
#    kubernetes.io/service-account.name: kruise-admin
#type: kubernetes.io/service-account-token
#---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: kruise
  name: kruise-argocd-manager-role
rules:
  - apiGroups: ["*"]
    resources: ["*"]
    verbs: ["*"]
