{{- if .Values.filebeat.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "kruise-standard-server.name" . }}-filebeat-config
  namespace: {{ .Release.Namespace }}
data:
  filebeat.yml: |
    filebeat.inputs:
      - type: filestream
        id: {{ include "kruise-standard-server.name" . }}-filestream
        parsers:
          - ndjson:
              target: ""
        paths:
          - {{ .Values.filebeat.logFilePath }}/{{ .Values.filebeat.logFileName }}
    output.elasticsearch:
      index: "{{ include "kruise-standard-server.name" . }}-%{[agent.version]}-%{+yyyy.MM.dd}"
      hosts:
        - "{{ .Values.filebeat.outputElasticsearchHost }}"
    setup.ilm.enabled: false
    setup.template:
      name: "{{ include "kruise-standard-server.name" . }}"
      pattern: "{{ include "kruise-standard-server.name" . }}-*"
      {{- end }}