apiVersion: v1
kind: Service
metadata:
  name: {{ include "kruise-standard-server.name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kruise-standard-server.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "kruise-standard-server.selectorLabels" . | nindent 4 }}
